version: 2.1 # CircleCI version
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      # Run all images that form our ongoing infrastructure
      - run: docker-compose up -d --build postgres graphql-engine ra-webserver
      # Run flyway without -d (attached) so that it blocks pgtap
      - run: docker-compose -f docker-compose-circleci.yaml up --exit-code-from flyway --build flyway
      - run: docker-compose -f docker-compose-circleci.yaml up --exit-code-from pgtap --build pgtap
      # Run our migrations for Hasura here so that it blocks whatever we use to API test eventually
      - run: docker-compose -f docker-compose-circleci.yaml up --exit-code-from graphql-migrations --build graphql-migrations
      # Our API test runner can go here eventually:
